"""Writes tikz_linking.tex: an HRU over 4 x 3 grid cells with its TRUE share in each cell (computed here with shapely),
and the recharge-volume bar chart. Needed only to regenerate the figure."""
from shapely.geometry import Polygon, box
from shapely.ops import polylabel
hru=Polygon([(0.42,0.38),(1.5,0.28),(2.5,0.5),(3.6,0.33),(3.5,1.5),(3.66,2.62),(2.4,2.74),(1.5,2.52),(0.34,2.7),(0.52,1.5)])
cells={(i,j):box(i,j,i+1,j+1) for i in range(4) for j in range(3)}
parts={k:hru.intersection(c) for k,c in cells.items() if hru.intersection(c).area>1e-9}
tot=sum(p.area for p in parts.values())
raw={k:100*p.area/tot for k,p in parts.items()}
fl={k:int(v) for k,v in raw.items()}; rest=100-sum(fl.values())
for k in sorted(raw,key=lambda k:-(raw[k]-fl[k]))[:rest]: fl[k]+=1    # largest remainders: shares add up to exactly 100
if __name__=='__main__':
    for k in sorted(raw): print(k,'%.2f%% -> %d%%'%(raw[k],fl[k]))
    print('sum',sum(fl.values()),' smallest %.2f%%'%min(raw.values()))
S=13  # mm per cell
L=[r'% HRU over grid cells with its share in each cell (generated by make_tikz_linking.py; shares computed from the shapes)',
   r'\begin{tikzpicture}[x=1mm,y=1mm,font=\sffamily\footnotesize,every node/.append style={execute at begin node={\hyphenpenalty=10000\exhyphenpenalty=10000}}]',
   r'\node[anchor=south west,font=\sffamily\small] at (0,%g) {(a) The HRU'"'"'s share in each cell};'%(3*S+4)]
L.append(r'\fill[teal!18] %s -- cycle;'%' -- '.join('(%.2f,%.2f)'%(x*S,y*S) for x,y in list(hru.exterior.coords)[:-1]))
for (i,j) in cells: L.append(r'\draw[black!45,line width=0.4pt] (%g,%g) rectangle (%g,%g);'%(i*S,j*S,(i+1)*S,(j+1)*S))
L.append(r'\draw[teal!70!black,line width=1.1pt] %s -- cycle;'%' -- '.join('(%.2f,%.2f)'%(x*S,y*S) for x,y in list(hru.exterior.coords)[:-1]))
for k,p in parts.items():
    c=polylabel(p,tolerance=0.005)   #the point of the piece farthest from its edges
    L.append(r'\node[font=\sffamily\bfseries\scriptsize,text=teal!45!black,inner sep=0.5pt] at (%.2f,%.2f) {%d\%%};'%(c.x*S,c.y*S,fl[k]))
L.append(r'\node[anchor=north,align=center,text width=50mm] at (%g,-2) {One HRU (green) over 12 grid cells.\\The shares add up to 100\%%.};'%(2*S))
# panel (b): volumes, bars of 70 mm for 50 000 m3
x0=64; W=48.0; sent=50000; given=0.92
rows=[(33,'Raven sends',sent,'brand',None),(19,'Arrives if the weights are used as they are\\\\(here they add up to only 92\\%)',sent*given,'red!65!black',sent*(1-given)),
      (5,'Arrives with Raven'"'"'s shares, which always\\\\add up to 100\\%',sent,'teal!70!black',None)]
L.append(r'\node[anchor=south west,font=\sffamily\small] at (%g,%g) {(b) 10\,mm of recharge on a 5\,km$^2$ HRU};'%(x0,3*S+4))
for y,lab,v,col,lost in rows:
    w=W*v/sent
    L.append(r'\node[anchor=south west,align=left,inner sep=0pt] at (%g,%g) {%s};'%(x0,y+3.2,lab))
    L.append(r'\fill[%s] (%g,%g) rectangle (%g,%g);'%(col,x0,y-2.5,x0+w,y+2.5))
    if lost:
        L.append(r'\draw[%s,pattern=north east lines,pattern color=%s] (%g,%g) rectangle (%g,%g);'%(col,col,x0+w,y-2.5,x0+W,y+2.5))
        L.append(r'\node[anchor=west,text=%s] at (%g,%g) {%s\,m$^3$ \ (4\,000\,m$^3$ lost)};'%(col,x0+W+1.5,y,'46\\,000'))
    else:
        L.append(r'\node[anchor=west] at (%g,%g) {%s\,m$^3$};'%(x0+w+1.5,y,'50\\,000'))
L.append(r'\end{tikzpicture}')
open('tikz_linking.tex','w').write('\n'.join(L)+'\n')
